### PR TITLE
Tasks 1, 2 & 3

### PR DESCRIPTION
**Pull request by romans91**
Will get to some more tasks in the morning.

### CODE REVIEW

**Comment by gmanley042** [comment]
Power draw display from Task 1 appears to be missing (line 23 in the index.html)

**Comment by romans91** [comment]
> Power draw display from Task 1 appears to be missing (line 23 in the index.html)

Interesting. It displays correctly on my screen. Do we both have .NET Framework 4.8 as the targeted framework? 
Targeted framework can be found by right clicking the project in solution explorere and pressing "Properties".

**Comment by gmanley042** [comment]
I mean its not been updated in the html, and the viewmodel does not seem to have the power draw applied to it?:
image

**Comment by romans91** [comment]
I found that too now and made a new commit. Looks like I didn't commit the viewmodel changes before. Should be fine now!

**Comment by romans91** [comment]
One moment, will re-commit changes to index.cshtml in a few seconds.

**Comment by gmanley042** [comment]
Looks good, thanks.

**Comment by romans91** [comment]
@gmanley042 I assume that we are at time, so I might leave it at three questions. I am brand new to JQuery, Knockout and Typescript so each step requires a lot of reading within the time constraints. It's been a pleasure working on this task and I look forward to mastering front end techniques should there be an opportunity in the future!

**Comment by gmanley042** [comment]
That's great - thanks for that. Looks good. We will be in touch.

**Pull request closed without merging**
